### ISSUE TITLE
regex under construction

### ISSUE THREAD

**Issue by hbdevelop1** [uri-templates/uritemplate-test#36]
Hello,
I am creating a regex for uri-templates and I need help with the following points:

1- In paragraphe 2.1.  Literals, it is mentioned that literals can any Unicode character except: CTL, SP, DQUOTE, "'", "%" (aside from pct-encoded), "<", ">", "\", "^", "`", "{", "|", "}"
I can’t find the name or the code for CTL, in any of the following resources:
https://en.wikipedia.org/wiki/C0_and_C1_control_codes
https://en.wikipedia.org/wiki/Unicode_control_characters
http://www.unicode.org/Public/UNIDATA/Index.txt
http://www.unicode.org/Public/UNIDATA/NamesList.txt
http://www.unicode.org/charts/PDF/U0000.pdf

Could you please tell me the name and the unicode code point for CTL?

2- I am testing my regex using the test cases provided in https://github.com/uri-templates/uritemplate-test.
My regex does match the following cases from negative-tests.json
            [ "{!hello}",  false  ] ,
            [ "{=path}",  false  ] ,
            [ "{|var*}", false ],
            [ "{keys:1}",  false  ],

2.1- The first 3 are matched because I have included the op-reserve ("=" / "," / "!" / "@" / "|") as legal operators. 
Should I remove them for now, and update my regex once they become used by the specification ?

2.2- I don’t know why is the last case wrong expression. Could you please explain ? 

Thank you very much in advance

Hassan

**Comment by sigmavirus24** [comment]
Question 1: Under section 1.5, it references other RFCs that it borrows definitions from. One such is RFC 5234. I'll let you read that for the exact definition of CTL.

Question 2.1:

>  Should I remove them for now, and update my regex once they become used by the specification ?

They're not used by the specification, so yes. I don't understand 2.2 but this isn't a support forum for the specification.

**Comment by mnot** [comment]
Note that URI templates aren't designed to allow unambiguous parsing of URLs into variables in every case; see:

https://tools.ietf.org/html/rfc6570#section-1.4

and #33.
