### ISSUE TITLE
How should hierarchical names (`.` separated) be expanded

### ISSUE THREAD

**Issue by jdesrosiers** [uri-templates/uritemplate-test#45]
> Structures are processed as if they are an associative array with names corresponding to the fields in the structure definition and "." separators used to indicate name hierarchy in substructures. https://tools.ietf.org/html/rfc6570#section-2.4.2

Given a composite value, `{ "foo": { "bar": "baz" } }`, and a URI Template, `{foo.bar}`, I expect this to expand to `baz`.

This is the only place in the spec where hierarchical names are discussed. There are no examples in the spec, there are no tests in this suite, and none of the implementations I tried support `.` as anything but a literal character in a variable name. So, I was hoping someone here could tell me if I've interpreted this part of the spec correctly. If not, what is it intended to mean?

**Comment by sigmavirus24** [comment]
I interpret it the same way. I suspect the python implementation that I maintain expects this to be a literal `.` in the name of the variable though. Primarily because this is such a subtle line and as you pointed out, there are no tests to catch this in an implementation

**Comment by jdesrosiers** [comment]
Great. Assuming this is the correct interpretation, what should the result of `{;foo.bar}` be? I think `;bar=baz` makes sense, but since the spec doesn't mention how to expand hierarchical names, I think it would have to be treated like any other name, `;foo.bar=baz` which is not very useful.

**Comment by sigmavirus24** [comment]
> Great

To be clear, I have nothing to do with the spec, so just because I interpret it the same way doesn't make us right. :)

> what should the result of `{;foo.bar}` be?

I'd argue that is completely undefined and so both `;foo.bar=baz` and `;bar=baz` are correct expansions here. It's unclear to me if any implementations deal with hierarchical names though so I personally would never rely upon it as any two implementations could handle these differently.

To make sure this does get defined, I would submit [errata](https://www.rfc-editor.org/errata_search.php?rfc=6570).

**Comment by jdesrosiers** [comment]
> To be clear, I have nothing to do with the spec

I understood that. At this point it's nice to know I wasn't just missing something obvious.

> I'd argue that is completely undefined and so both `;foo.bar=baz` and `;bar=baz` are correct expansions here.

Agreed. Unfortunately, that makes names with `.` both allowed and completely unreliable/useless.

> To make sure this does get defined, I would submit errata.

I was going to submit an errata if I don't manage to get a response from the authors, but I'd rather discuss it with them first in case we're missing something despite our consensus.

**Comment by sigmavirus24** [comment]
I believe your best way to get the attention of the authors is to file the errata. I don't believe they monitor this repository or issue tracker very closely

**Comment by mnot** [comment]
That's not errata material; it's something that we didn't attempt to address in the specification, as it would require defining a data model. Implementations choose how to map identifiers into data.

All that said, a new level could attempt this (as an add-on spec).

Closing this as it's not about the test suite. If you want to pursue this, a few options:

1. Send e-mail to art@ietf.org
2. Wait for the proposed HTTP APIs WG to start (should be very soon), and engage there
3. Write an Internet-Draft with a proposal

Cheers,
