### ISSUE TITLE
Lists should be ordered?

### ISSUE THREAD

**Issue by awwright** [uri-templates/uritemplate-test#46]
The extended tests suggest that lists are unordered, however I cannot find any basis for this.

The spec doesn't mention ordered/unordered, however the word "list" usually implies an ordering (in contrast to "set"), and in this particular example, it would be very odd if the the order of a list in the _hierarchical part_ didn't matter (notice how "albums" and "person" are listed in both orders):

https://github.com/uri-templates/uritemplate-test/blob/520fdd8b0f78779d12178c357a986e0e727f4bd0/extended-tests.json#L71-L83

**Comment by mnot** [comment]
`?` indicates [form-style query expansion](https://www.rfc-editor.org/rfc/rfc6570.html#section-3.2.8), and non-matching query parameters are unordered (i.e., the forms above are all considered equivalent).

Perhaps you're reading too much into the example variable name 'list' in the spec?

**Comment by awwright** [comment]
@mnot But what about in the `/` operator in that test? It permits either `/person` or `/albums` to be first.

Meanwhile, none of the examples in `spec-examples.json` permit reordering, e.g.:

https://github.com/uri-templates/uritemplate-test/blob/520fdd8b0f78779d12178c357a986e0e727f4bd0/spec-examples.json#L141

I'm researching the reversible subset of URI Templates, and this inconsistency means I can't get both tests to pass.

**Comment by mnot** [comment]
OK, so I think this is more about the [explode modifier](https://www.rfc-editor.org/rfc/rfc6570.html#section-2.4.2) (`*`), which says:

> An explode modifier applied to a list variable causes the expansion to iterate over the list's member values.

... So on the face of it, the options starting with `/albums/person` should be removed.

@damnhandy, you added these in #5. Any thoughts? It would be interesting to see if any implementations broke if we moved these into `negative-tests.json`...

**Comment by mk-pmb** [comment]
I as well expect order to be kept. Otherwise it would totally break paths, and also elements from a listbox form element whose ordering uses have chosen carefully.

**Comment by damnhandy** [comment]
@mnot I think I agree with you here. I can probably test this out later in the week. I suspect a lot of implementations would maintain declaration order so I don't think there'd be a lot of breakage. This would need some more testing beyond a single implementation. 

@awwright  for years, I've had a feature request for my implementation to do reverse matching. It's issues like this one that made it more effort that it was probably worth to invest time into. The more complicated the template, the tougher the match. Had there been more specifics around ordering, it might have been easier to implement.

**Comment by awwright** [comment]
@damnhandy Yeah, as far as I can tell, the ordering is the final problem for reversing URI templates. Certain features are difficult to implement (re-using a variable increases the computational complexity from linear to exponential) or impossible (substrings). But for the most part, it's entirely possible, so long as it's deterministic (either everything needs to be an unordered set, or it needs to preserve the list ordering).
