### ISSUE TITLE
Conflicting expectations?

### ISSUE THREAD

**Issue by savagematt** [uri-templates/uritemplate-test#61]
In `spec-examples-by-section.json`:

`{?x,y,empty}` with no value for `empty` expects:
`?x=1024&y=768&empty=`
(i.e. param with no value appears as query param)

In `extended-tests.json`:

`/search.{format}{?q,geocode,lang,locale,page,result_type}` with no `locale` value expects:
 `/search.json?q=URI%20Templates&geocode=37.76,-122.427&lang=en&page=5` 
 (i.e. no locale query param appears in expanded uri)

Am I missing something or is the expectation in the extended test incorrect according to the spec?

**Comment by alexdeem** [comment]
The test in `spec-examples-by-section.json` does have a value for `empty`: it is specified in the variables as `""` ie. the empty string.

In the other test `locale` is not specified in the input variables at all.

**Comment by savagematt** [comment]
Aaah. It's my fault- my tests were modifying the json before running, I should have gone directly to the source files.

Thanks Alex, apologies for wasting your time.

**Comment by alexdeem** [comment]
I'm glad to have helped; not at all a waste of my time. 😄

**Comment by savagematt** [comment]
Cheers Alex. 

Out of interest here's a Typescript implementation that passes the spec and uses template literals to give you type safe expansions just from the template string. Not sure what I'm going to do with it yet- seems over-engineered in a way that's not necessarily a pleasant developer experience, but it is interesting that it's possible.

https://github.com/http4t/http4t/blob/uri-template/packages/core/test/uriTemplate/expansion.test.ts

https://github.com/http4t/http4t/blob/uri-template/packages/core/src/UriTemplate.ts
